services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf_translator_frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - pdf_translator
    restart: unless-stopped

  api:
    build:
      context: ./2025-lambda-pdf-translator-api/app
      dockerfile: Dockerfile.prod
    container_name: pdf_translator_api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - PORT=3333
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-secret-key-here
    networks:
      - pdf_translator
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: pdf_translator_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./2025-lambda-pdf-translator-api/docker/db/psql_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pdf_translator
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pdf_translator:
    driver: bridge